version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  sync:
    cmds:
      - git add .
      - git commit -m "auto-sync"
      - git push
      - git switch main
      - git merge dev
      - git push
      - git switch dev

  marp:
    cmds:
      - echo 'Building...'
      - echo 'running marp .'
      - marp .

  build:
    cmds:
      - echo 'running templ generate...'
      - templ generate
      - echo 'running go run...'
      - go run ./cmd/main.go
      - echo 'running tsc build...'
      - tsc --build
      - echo 'running npx tailwindcss...'
      - npx tailwindcss -i ./input.css -o ./docs/styles/styles.css
