version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    cmds:
      - echo 'Building...'
      - tsc --build
      - npx tailwindcss -i ./input.css -o ./docs/styles/styles.css
    silent: true
